{% set name = "anywidget" %}
{% set version = "0.9.10" %}
{% set sha256 = "390a628240981c09813c7523279ddcab82ff4fd3287add5433b78b1369089068" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anywidget-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: {{ environ.get('BUILD_NUMBER', 0) }}

requirements:
  host:
    - python >=3.10
    - hatchling
    - hatch-jupyter-builder
    - jupyterlab
    - pip
  run:
    - python >=3.7
    - ipywidgets
    - psygnal
    - typing_extensions
    - watchfiles

test:
  imports:
    - anywidget

about:
  home: https://pypi.org/project/anywidget/
  summary: simple, custom Jupyter widgets
  description: |
    anywidget is a Python library that greatly simplifies creating and publishing 
    custom Jupyter Widgets.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/manzt/anywidget