{% set name = "jenkspy" %}
{% set version = "0.4.1" %}
{% set sha256 = "e61e2103bed031cdfac9996604308298bc0a29f8051f09c343d9ce35af32a1f3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jenkspy-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler("c") }}
    - python                                 # [build_platform != target_platform]
  host:
    - cython
    - pip
    - python
    - setuptools >=61.0
  run:
    - numpy
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - jenkspy

about:
  home: http://github.com/mthh/jenkspy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Compute Natural Breaks (Fisher-Jenks algorithm)
  description: Compute natural breaks (Fisher-Jenks algorithm) on list/tuple/array/numpy.ndarray of integers/floats.
  dev_url: https://github.com/mthh/jenkspy