name: anywidget

on:
  workflow_dispatch:

env:
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.11
    - name: Setup
      id: setup-build-environment
      run: |
        conda install conda-build conda-verify python=3.11 -y
        # output .conda packages
        conda config --set conda_build.pkg_format 2
    - name: build
      run: |
        conda build -c https://esri-forge.python.geocloud.com anywidget --output-folder ./output
    - name: List outputs
      run: |
        ls -R ./output
    - uses: actions/upload-artifact@v4
      with:
        name: anywidget-${{ github.sha }}
        path: output/**/*.conda
        retention-days: 90