name: pydantic-core

on:
  workflow_dispatch:

env:
  BUILD_NUMBER: ${{ github.run_number }}
  UPLOAD_PACKAGES: False
  IS_PR_BUILD: False

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
        fail-fast: false
        matrix:
            os:
              - macos-13 # Intel x64
            config:
              - "osx_64_python3.10.____cpython"
              - "osx_64_python3.11.____cpython"
              - "osx_64_python3.12.____cpython"
              - "osx_64_python3.13.____cp313"
    steps:
    - uses: actions/checkout@v4
    - name: Run OSX build
      id: run-osx-build
      run: |
        export CONFIG=${{ matrix.config }}
        export CI=azure
        export flow_run_id=${{ github.run_id }}.${{ github.run_number }}
        export remote_url=${GITHUB_SERVER_URL}/${{ github.repository }}
        export sha=${{ github.sha }}
        export OSX_FORCE_SDK_DOWNLOAD="1"
        export GIT_BRANCH=${{ github.ref_name }}
        export FEEDSTOCK_NAME=pydantic-core-feedstock
        ./.scripts/run_osx_build.sh
    - name: List outputs
      run: |
        ls -R ./output
    - uses: actions/upload-artifact@v4
      with:
        name: pydantic-core-${{ matrix.os }}-${{ matrix.python-version }}-${{ github.sha }}
        path: output/**/*.conda
        retention-days: 90